# Generated by debtap
# Maintainer: sentinelone
# Contributor: sentinelone
pkgname=sentinelagent
pkgver=3.0.7.21
pkgrel=1
pkgdesc="SentinelOne | Next-Generation Endpoint Protection Software."
arch=('i686' 'x86_64')
url=""
license=('none')
groups=('')
depends=('kmod')
options=('!strip' '!emptydirs')
install=${pkgname}.install
source=("data.tar.xz")
md5sums=('SKIP')
#source_i686=("PUT_FULL_URL_FOR_DOWNLOADING_i386_DEB_PACKAGE_HERE")
#source_x86_64=("PUT_FULL_URL_FOR_DOWNLOADING_amd64_DEB_PACKAGE_HERE")
#sha512sums_i686=('PUT_SHA512SUM_OF_i386_DEB_PACKAGE_HERE')
#sha512sums_x86_64=('be7914d935ddae7c7bdf63fb2eefa2bec8c9eecd6970865e94655356b692c5ec284a897b538efb9df199ecd6919e9d3695fe0df56a2bf7d3c186bf11d7543473')

package(){

	# Extract package data
	tar xf data.tar.xz -C "${pkgdir}"

}
